/* eslint-disable camelcase */
export const LOGIN_USER = 'LOGIN_USER';
export const GET_All_USER_ORDERS = 'GET_All_USER_ORDERS';
export const GET_DELIVERED_USER_ORDERS = 'GET_DELIVERED_USER_ORDERS';
export const GET_INTRANSIT_USER_ORDERS = 'GET_INTRANSIT_USER_ORDERS';
export const GET_CREATED_USER_ORDERS = 'GET_CREATED_USER_ORDERS';
export const GET_CANCELED_USER_ORDERS = 'GET_CANCELED_USER_ORDERS';
export const GET_All_USERS = 'GET_All_USERS';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
